# Generated by Django 5.1.6 on 2025-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='img',
            field=models.ImageField(default='https://www.pngall.com/wp-content/uploads/8/Restaurant-Logo-PNG-Image-File.png', upload_to=''),
        ),
    ]
